name: Run CI
on:
  pull_request:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "compiler"
  INPUT_FILENAME: "main.vala"
  OUTPUT_FILENAME: "main"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends libguestfs-tools qemu-user-static binfmt-support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.IMAGE_NAME }}
      # - name: Compile binary
      #   run: docker run --rm -v $PWD:/app -w /app -u 0:0 ${{ env.IMAGE_NAME }} -o ${{ env.OUTPUT_FILENAME }} ${{ env.INPUT_FILENAME }}
